---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install nginx
  apt: name=nginx state=present
  become: yes

- name: de-activate default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
  
- name: ensure nginx started
  service: name=nginx state=started enabled=yes

- name: configure nginx sites
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default mode=0644

- name: add wordpress nginx site
  template: src=nginx.conf.wordpress.j2 dest=/etc/nginx/sites-available/worpress mode=0644

- name: activate nginx sites
  file: src=/etc/nginx/sites-available/worpress dest=/etc/nginx/sites-enabled/worpress state=link
  notify: restart nginx