---
- name: install tools
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - python-httplib2

- name: install nginx
  apt: name=nginx state=present update_cache=yes

- name: configure nginx sites
  template: src=load-balancer.conf.j2 dest=/etc/nginx/conf.d/load-balancer.conf mode=0644
  notify: restart nginx

- name: de-activate default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

#- name: activate nginx sites
#  file: src=/etc/nginx/sites-available/wordpress dest=/etc/nginx/sites-enabled/default state=link
#  notify: restart nginx

- name: ensure nginx started
  service: name=nginx state=started enabled=yes