---
- name: Download WordPress  
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/latest.tar.gz
    validate_certs=no 
  become: yes

- name: Extract WordPress  
  unarchive: src=/tmp/latest.tar.gz dest=/tmp/ copy=no 
  become: yes

- name: get WordPress secret keys
  shell: curl -s https://api.wordpress.org/secret-key/1.1/salt/
  register: secretkeys

- name: configure wordpress sites
  template: src=wp-config.php.j2 dest=/tmp/wordpress/wp-config.php mode=0644

- name: Clean /var/www/html
  file:
    state: absent
    path: /var/www/html

- name: ensure /var/www/ exists
  file:
    state: directory
    path: /var/www/

- name: Move wordpress files to /var/www/html
  command: mv /tmp/wordpress /var/www/html

- file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes

- file:
    path: /var/www/html/wp-content/uploads
    state: directory
    group: www-data
    recurse: yes

