- hosts: mysql
  tasks:
    - name: Ensure mysql service is stopped
      service:
        name: mysql
        state: stopped
      ignore_errors: yes

    - name: Remove mysql
      apt: name={{ item }} state=absent purge=yes
      become: yes
      with_items:
        - mysql-server    
        - mysql-client
        - mysql-common
        - mysql-server-core-*
        - mysql-client-core-*
        
    - name: Clean up files created by nginx-simple
      file:
        name: "{{ item }}"
        state: absent
      with_items:
        - /etc/mysql 
        - /var/lib/mysql
        - /var/log/mysql

    - name: Autoremove
      apt: autoremove=yes
      become: yes